name: Build and Deploy AGV Web App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4

      - name: Install dependencies (frontend)
        working-directory: .\frontend
        run: npm ci

      - name: Build frontend (Vite)
        working-directory: .\frontend
        run: npm run build

      - name: Install backend dependencies
        working-directory: .\backend
        run: npm ci
